using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

public class TemplateLoader
{
    public List<(XElement Tiles, XElement Enemies)> LoadTemplates(string sourceXmlPath, int templateLimit = 16)
    {
        XDocument sourceDoc = XDocument.Load(sourceXmlPath);


        // Generated by Gemini AI: Uses LINQ-to-XML to grab the 
        // tiles from the first [templateLimit] Rooms in the sourceXmlPath
        var templates = sourceDoc.Descendants("Room") // This scans the entire XML tree to find all "Room" elements
                         .Where(r => {
                             int row = (int?)r.Attribute("row") ?? -1; // Gets the row attribute of the room tag and converts it to an int or -1 if can't find attribute
                             int col = (int?)r.Attribute("col") ?? -1; // Gets the col attribute of the room tag

                             return
                                    col > 0 && col != 99;
                         }) // Filters the rooms whose "col" attribute is more than 0
                         .Take(templateLimit) // Limits the results to the template limit
                         .Select(r => (
                         Tiles: r.Element("Tiles"),
                         Enemies: r.Element("Enemies")
                         )) // Goes from the room tags to the tiles tags in the individual rooms
                         .Where(t => t.Tiles != null) // Filters out any rooms wihtout Tiles tags --> Safety check against NullRefExcpetion
                         .ToList(); // Executes the query and saves the collection of Tiles into a usable list

        if (templates.Count == 0)
        {
            throw new Exception("No templates found in source XML!");
        }

        return templates;
    }
}